import { z } from 'zod';
import { idSchema } from './common';

/** What the browser reports after uploading a chat photo to Cloudinary. */
const attachmentSchema = z.object({
  publicId: z.string().max(200).regex(/^[A-Za-z0-9_/-]+$/, 'Invalid photo'),
  version: z.number().int().positive(),
  signature: z.string().regex(/^[a-f0-9]{40}$/, 'Invalid photo'),
});

export const sendMessageSchema = z
  .object({
    content: z.string().trim().max(2000, 'Message cannot exceed 2000 characters').default(''),
    /** A photo (uploaded first); the text is then optional. */
    attachment: attachmentSchema.optional(),
    /** Generated by the client per message and reused on retries, so a message is stored once. */
    clientMessageId: z.string().uuid('Invalid client message id').optional(),
  })
  .refine((m) => m.content.length > 0 || m.attachment, { message: 'Message cannot be empty', path: ['content'] });

/** Cursor pagination: `before` is the id of the oldest message the client already has. */
export const messagePageSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(50),
  before: idSchema.optional(),
});

export type SendMessageInput = z.infer<typeof sendMessageSchema>;
export type MessagePageQuery = z.infer<typeof messagePageSchema>;
