import { z } from 'zod';
import { idSchema } from './common';

export const sendMessageSchema = z.object({
  content: z
    .string()
    .trim()
    .min(1, 'Message cannot be empty')
    .max(2000, 'Message cannot exceed 2000 characters'),
  /** Generated by the client per message and reused on retries, so a message is stored once. */
  clientMessageId: z.string().uuid('Invalid client message id').optional(),
});

/** Cursor pagination: `before` is the id of the oldest message the client already has. */
export const messagePageSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(50),
  before: idSchema.optional(),
});

export type SendMessageInput = z.infer<typeof sendMessageSchema>;
export type MessagePageQuery = z.infer<typeof messagePageSchema>;
